Repository CMIPT/gcs-back-end, pull requests merged in 2024-08, with the labels that each got.

#22 Remove unsed dependency and add doc for configuration
  README-zh.md
  config_debug.json
  config_default.json
  pom.xml
  script/deploy_helper.py
  src/main/java/edu/cmipt/gcs/controller/SwaggerTmpController.java
  src/test/java/edu/cmipt/gcs/GcsApplicationTest.java
  src/test/java/edu/cmipt/gcs/controller/SwaggerTmpControllerITest.java
  src/test/java/edu/cmipt/gcs/controller/SwaggerTmpControllerTest.java
  src/test/java/edu/cmipt/gcs/controller/SwaggerTmpControllerTests.java
Labels: bug, documentation

#17 Add command_checker and setup_logger to script/deploy_helper.py
  pom.xml
  script/deploy_helper.py
Labels: project initialization

#24 Finish the script for deploying in docker
  README-zh.md
  config_debug_docker.json
  config_default.json
  deploy_ubuntu.sh
  script/deploy_helper.py
  script/service_tmp.sh
Labels: documentation, project initialization

#25 Finish the deploy script for database
  README-zh.md
  config_debug.json
  config_debug_docker.json
  config_default.json
  config_user.json
  database/database_deploy.sh
  database/table/t_repository.sql
  database/table/t_user.sql
  database/table/t_user_repository.sql
  deploy_ubuntu.sh
  script/deploy_helper.py
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: project initialization

#29 Configure datasource and mybatis-plus
  .github/workflows/java-format.yml
  .gitignore
  README-zh.md
  config_debug.json
  config_default.json
  pom.xml
  script/deploy_helper.py
  src/main/java/edu/cmipt/gcs/GcsApplication.java
  src/main/java/edu/cmipt/gcs/config/DruidConfig.java
  src/main/java/edu/cmipt/gcs/dao/UserMapper.java
  src/main/java/edu/cmipt/gcs/pojo/UserPO.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/edu/cmipt/gcs/controller/dao/UserMapperTest.java
Labels: project initialization

#31 Update the primary key of database
  database/constraint/all_column_constraint.sql
  database/database_deploy.sh
  database/diagram/gcs_back_end.drawio
  database/diagram/gcs_back_end.png
  database/function/update_gmt_updated_column.sql
  database/sequence/all_column_seq.sql
  database/sequence/sequence_set.sql
  database/table/t_repository.sql
  database/table/t_user.sql
  database/table/t_user_repository.sql
  database/trigger/all_table_trigger.sql
Labels: bug, enhancement

#33 Finish the example for creating a user
  database/diagram/gcs_back_end.drawio
  database/diagram/gcs_back_end.png
  database/table/t_user.sql
  src/main/java/edu/cmipt/gcs/controller/SwaggerTmpController.java
  src/main/java/edu/cmipt/gcs/controller/UserController.java
  src/main/java/edu/cmipt/gcs/dao/UserMapper.java
  src/main/java/edu/cmipt/gcs/pojo/UserPO.java
  src/main/java/edu/cmipt/gcs/pojo/user/UserDTO.java
  src/main/java/edu/cmipt/gcs/pojo/user/UserPO.java
  src/main/java/edu/cmipt/gcs/service/UserService.java
  src/main/java/edu/cmipt/gcs/service/UserServiceImpl.java
  src/main/java/edu/cmipt/gcs/util/MD5Converter.java
  src/main/resources/application.yml
  src/test/java/edu/cmipt/gcs/controller/SwaggerTmpControllerITest.java
  src/test/java/edu/cmipt/gcs/controller/UserControllerTest.java
  src/test/java/edu/cmipt/gcs/dao/UserMapperTest.java
Labels: feature

#34 Add an example for validation
  pom.xml
  src/main/java/edu/cmipt/gcs/config/.gitkeep
  src/main/java/edu/cmipt/gcs/controller/UserController.java
  src/main/java/edu/cmipt/gcs/exception/GlobalExceptionHandler.java
  src/main/java/edu/cmipt/gcs/pojo/user/UserDTO.java
  src/main/java/edu/cmipt/gcs/pojo/user/UserPO.java
  src/main/java/edu/cmipt/gcs/util/MessageSourceUtil.java
  src/main/java/edu/cmipt/gcs/validation/ConstantProperty.java
  src/main/java/edu/cmipt/gcs/validation/group/CreateGroup.java
  src/main/java/edu/cmipt/gcs/validation/group/UpdateGroup.java
  src/main/resources/application.yml
  src/main/resources/message/message.properties
  src/test/java/edu/cmipt/gcs/controller/UserControllerTest.java
Labels: feature

#35 User record to define the DTO object
  src/main/java/edu/cmipt/gcs/pojo/user/UserDTO.java
  src/main/java/edu/cmipt/gcs/pojo/user/UserPO.java
Labels: enhancement

#37 Add filter for authentication and authorization
  pom.xml
  src/main/java/edu/cmipt/gcs/constant/ApiPathConstant.java
  src/main/java/edu/cmipt/gcs/constant/ApplicationConstant.java
  src/main/java/edu/cmipt/gcs/constant/ErrorMessageConstant.java
  src/main/java/edu/cmipt/gcs/constant/ValidationConstant.java
  src/main/java/edu/cmipt/gcs/controller/AuthenticationController.java
  src/main/java/edu/cmipt/gcs/controller/DevelopmentController.java
  src/main/java/edu/cmipt/gcs/controller/UserController.java
  src/main/java/edu/cmipt/gcs/enumeration/TokenTypeEnum.java
  src/main/java/edu/cmipt/gcs/exception/AccessDeniedException.java
  src/main/java/edu/cmipt/gcs/exception/GlobalExceptionHandler.java
  src/main/java/edu/cmipt/gcs/filter/ExceptionHandlerFiter.java
  src/main/java/edu/cmipt/gcs/filter/JwtFilter.java
  src/main/java/edu/cmipt/gcs/pojo/error/ErrorVO.java
  src/main/java/edu/cmipt/gcs/pojo/user/UserDTO.java
  src/main/java/edu/cmipt/gcs/pojo/user/UserSignInDTO.java
  src/main/java/edu/cmipt/gcs/pojo/user/UserVO.java
  src/main/java/edu/cmipt/gcs/util/ErrorMessageUtil.java
  src/main/java/edu/cmipt/gcs/util/JwtUtil.java
  src/main/resources/message/message.properties
  src/test/java/edu/cmipt/gcs/controller/AuthenticationControllerTest.java
  src/test/java/edu/cmipt/gcs/controller/UserControllerTest.java
Labels: feature

#38 Update the processing of error messages
  src/main/java/edu/cmipt/gcs/constant/ErrorMessageConstant.java
  src/main/java/edu/cmipt/gcs/constant/HeaderParameter.java
  src/main/java/edu/cmipt/gcs/controller/AuthenticationController.java
  src/main/java/edu/cmipt/gcs/controller/DevelopmentController.java
  src/main/java/edu/cmipt/gcs/enumeration/ErrorCodeEnum.java
  src/main/java/edu/cmipt/gcs/exception/AccessDeniedException.java
  src/main/java/edu/cmipt/gcs/exception/GenericException.java
  src/main/java/edu/cmipt/gcs/exception/GlobalExceptionHandler.java
  src/main/java/edu/cmipt/gcs/filter/JwtFilter.java
  src/main/java/edu/cmipt/gcs/pojo/error/ErrorVO.java
  src/main/java/edu/cmipt/gcs/pojo/user/UserDTO.java
  src/main/java/edu/cmipt/gcs/pojo/user/UserSignInDTO.java
  src/main/java/edu/cmipt/gcs/util/ErrorMessageUtil.java
  src/main/java/edu/cmipt/gcs/util/JwtUtil.java
  src/main/java/edu/cmipt/gcs/util/MD5Converter.java
  src/main/java/edu/cmipt/gcs/util/MessageSourceUtil.java
  src/main/resources/message/message.properties
  src/test/java/edu/cmipt/gcs/controller/AuthenticationControllerTest.java
  src/test/java/edu/cmipt/gcs/dao/UserMapperTest.java
Labels: enhancement, refactor

#39 Add configuration for CORS
  README-zh.md
  config_default.json
  script/deploy_helper.py
  src/main/java/edu/cmipt/gcs/config/WebConfig.java
  src/main/java/edu/cmipt/gcs/constant/ApplicationConstant.java
  src/test/java/edu/cmipt/gcs/config/WebConfigTest.java
  src/test/java/edu/cmipt/gcs/controller/AuthenticationControllerTest.java
Labels: feature
